name: Deploy demo app

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  deploy-demo-app:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build demo-reset image on host
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: demo.activities.training
          username: builder
          key: ${{ secrets.BUILDER_SSH_PRIVATE_KEY }}
          script: /usr/local/bin/build-demo-reset.sh

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: activities-demo
          file: infra/demo/docker-stack.yaml
          host: demo.activities.training
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
