name: Deploy demo app

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  build-demo-reset:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push demo-reset image
        uses: docker/build-push-action@v5
        with:
          context: infra/demo
          file: infra/demo/Dockerfile.reset
          push: true
          platforms: linux/arm64
          tags: ghcr.io/thomas-god/activities-demo-reset:latest

  deploy-demo-app:
    runs-on: ubuntu-latest
    needs: build-demo-reset
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: activities-demo
          file: infra/demo/docker-stack.yaml
          host: demo.activities.training
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
