name: Release

on:
  release:
    types: [published]

jobs:
  build-docker-image:
    strategy:
      matrix:
        feature: ["single-user", "multi-user"]
        arch: ["amd64", "arm64"]
        include:
          - arch: amd64
            runs_on: ubuntu-24.04
            platform: linux/amd64
            cache_key: service-amd64-buildx-cache
          - arch: arm64
            runs_on: ubuntu-24.04-arm
            platform: linux/arm64
            cache_key: service-arm64-buildx-cache
    runs-on: ${{ matrix.runs_on }}
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache the Cargo dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ matrix.cache_key }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: ./docker/Dockerfile
          build-args: |
            APP_FEATURE=${{ matrix.feature }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/thomas-god/activities:${{ matrix.feature }}-${{ github.event.release.tag_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache to original location
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests/${{ matrix.feature }}
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${{ matrix.feature }}/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.feature }}-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/${{ matrix.feature }}/*
          if-no-files-found: error
          retention-days: 1

  # Taken from https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
  merge:
    runs-on: ubuntu-24.04
    needs:
      - build-docker-image
    strategy:
      matrix:
        feature: ["single-user", "multi-user"]
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests/${{ matrix.feature }}
          pattern: digests-${{ matrix.feature }}-*
          merge-multiple: true

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/thomas-god/activities
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}},prefix=${{ matrix.feature }}-
            type=semver,pattern={{major}}.{{minor}},prefix=${{ matrix.feature }}-
            type=semver,pattern={{major}},prefix=${{ matrix.feature }}-
            type=raw,value=${{ matrix.feature }}-latest

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests/${{ matrix.feature }}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf 'ghcr.io/thomas-god/activities@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ghcr.io/thomas-god/activities:${{ steps.meta.outputs.version }}
